image: rust:latest

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

stages:
  - prepare-test
  - test

variables:
  CARGO_HOME: "${CI_PROJECT_DIR}/.cargo"

cache:
  paths:
    - .cargo/bin/
    - .cargo/.crates.toml
    - .cargo/.crates2.json
    - .cargo/registry/index/
    - .cargo/registry/cache/
    - .cargo/git/db/
    - target/

prepare:
  stage: prepare-test
  script:
    - cargo install cargo-nextest
    - cargo install cargo-tarpaulin
    - cargo install cargo-deny

test:
  stage: test
  script:
    - rustup component add rustfmt
    - cargo nextest run --no-fail-fast
    - cargo tarpaulin --ignore-tests
  coverage: '/^\d+.\d+% coverage/'
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ '/^(development|main|production)$/'

lint:
  stage: test
  script:
    - rustup component add rustfmt
    - rustup component add clippy
    - cargo clippy -- -D warnings
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ '/^(development|main|production)$/'
    
format:
  stage: test
  script:
    - rustup component add rustfmt
    - cargo fmt --check
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ '/^(development|main|production)$/'

audit:
  stage: test
  script:
    - cargo deny check
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ '/^(development|main|production)$/'
