workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
        && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ '/^(development|main|production)$/'

stages:
  - build
  - install-test-tools
  - test

include: .gitlab/ci/test.yml

build:
  stage: build
  cache:
    - <<: *cargo_registry
      policy: pull-push
    - <<: *cargo_artifacts
      policy: pull-push
  script:
    - cargo build
