apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: user-management-microservice-pubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
    - name: redisHost
      value: localhost:6380
    - name: redisPassword
      value: ""
