CREATE TABLE prefilled_individual_contractors_details_for_bulk_upload (
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    client_ulid uuid NOT NULL,
    branch_ulid uuid NOT NULL,
    department_ulid uuid,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    gender TEXT,
    marital_status TEXT,
    nationality TEXT NOT NULL,
    dob date NOT NULL,
    dial_code TEXT NOT NULL,
    phone_number TEXT NOT NULL,
    email TEXT NOT NULL PRIMARY KEY,
    address TEXT,
    country TEXT,
    city TEXT,
    postal_code TEXT,
    national_id TEXT,
    passport_number TEXT,
    passport_expiry_date TEXT,
    work_permit TEXT,
    tax_id TEXT,
    contribution_id_1 TEXT,
    contribution_id_2 TEXT,
    total_dependants SMALLINT,
    time_zone TEXT,
    employee_id TEXT,
    designation TEXT,
    start_date DATE,
    end_date DATE,
    employment_status TEXT,
    bank_name TEXT,
    bank_account_owner_name TEXT,
    bank_account_number TEXT,
    bank_code TEXT,
    bank_branch_code TEXT,
    currency CURRENCY,
    basic_salary DECIMAL,
    additional_item_1 TEXT,
    additional_item_2 TEXT,
    deduction_1 TEXT,
    deduction_2 TEXT,
    other_pay_item_1 TEXT,
    other_pay_item_2 TEXT
);

CREATE TRIGGER mdt_prefilled_individual_contractors_details_for_bulk_upload BEFORE UPDATE ON prefilled_individual_contractors_details_for_bulk_upload FOR EACH ROW EXECUTE FUNCTION public.moddatetime('updated_at');

