image: rust:latest

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ '/^(development|main|production)$/'

stages:
  - prepare
  - test

variables:
  CARGO_HOME: "${CI_PROJECT_DIR}/.cargo"

default:
  cache:
    - &default_cache
      key: default
      paths:
        - .cargo/registry/index/
        - .cargo/registry/cache/
        - .cargo/git/db/
        - target/
      policy: pull
    - &cargo_install_cache
      key: default
      paths:
        - .cargo/bin/
        - .cargo/.crates.toml
        - .cargo/.crates2.json
      policy: pull
  before_script:
    - rustup component add rustfmt

build:
  stage: prepare
  extends: default
  cache:
    - <<: *default_cache
      policy: pull-push
  script:
    - cargo build

install-tools:
  stage: prepare
  cache:
    - <<: *default_cache
      policy: pull-push
    - <<: *cargo_install_cache
      policy: pull-push
  script:
    - cargo install cargo-nextest
    - cargo install cargo-tarpaulin
    - cargo install cargo-deny

test:
  stage: test
  script:
    - cargo nextest run --no-fail-fast

coverage:
  stage: test
  cache:
    - <<: *default_cache
      policy: pull-push
    - <<: *cargo_install_cache
  script:
    - cargo tarpaulin --ignore-tests --skip-clean --target-dir target/coverage/
  coverage: '/^\d+.\d+% coverage/'

lint:
  stage: test
  script:
    - rustup component add clippy
    - cargo clippy -- -D warnings
    
format:
  stage: test
  script:
    - cargo fmt --check

audit:
  stage: test
  script:
    - cargo deny check
